산불발생은 1, 산불 미발생은 0로 표기한 2014-2020년 학습용 데이터 만들기

In [153]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [154]:
df1=pd.read_csv('fire_7yr_specific_local.csv')
df2=pd.read_csv('weather_7yr_specific_local_mean.csv')
#발생장소_시도,관측일로 inner join
df = pd.merge(left=df2, right=df1, how='outer', on=['발생장소_시도','관측일'])

In [155]:
#산불발생여부를 구분할 열 만들기(산불발생은 1, 미발생은 0으로 표기)
fire=[]
for row in df['발생원인_구분']:
    if (row=='입') |(row=='기') | (row=='쓰') | (row=='담') | (row=='건') :
        fire.append(1)
    else:
        fire.append(0)

df.insert(0,"산불발생건수", fire,True)

In [156]:
df2=df[['산불발생건수', '발생장소_시도', '관측일', '평균기온', '일최고기온', '일최고기온시각', '일최저기온',
       '일최저기온시각', '일평균현지기압', '일최고현지기압', '일최고현지기압시각', '일최저현지기압', '일최저현지기압시각',
       '일평균해면기압', '일최고해면기압', '일최고해면기압시각', '일최저해면기압', '일최저해면기압시각', '일평균상대습도',
       '일최소상대습도', '일최소상대습도시각', '일평균수증기압', '일최고수증기압', '일최고수증기압시각', '일최저수증기압',
       '일최저수증기압시각', '일평균풍속', '일합성풍속', '일합성풍향', '일최대풍속', '일최대풍속시각', '일최대풍속풍향',
       '일최대순간풍속', '일최대순간풍속시각', '일최대순간풍속풍향', '풍정합', '일최다풍향', '일강수량', '10분최다강수량',
       '10분최다강수량시각', '1시간최다강수량', '1시간최다강수량시각', '9_9 강수량', '일최심신적설', '일최심신적설시각',
       '일최심적설', '일최심적설시각', '합계깊이신적설', '일평균전운량', '일평균중하층운량', '최저운고', '최저운고시각',
       '최다운량', '최다운량시각', '일합계일조시간', '일합계일사량', '일합계소형증발량', '일합계대형증발량',
       '일평균지면온도', '일평균이슬점온도']]

In [157]:
X=df2.평균기온.values
Y=df2.산불발생건수.values
#공분산
np.cov(X,Y)[0,1]

-0.4042265218877455

In [158]:
#공분산은 상관관계의 상승 혹은 하강하는 경향을 이해할 수는 있으나 2개 변수의 측정 단위의 크기에 따라 값이 달라지므로 절대적 정도를 파악하기에는 한계가 있음. 예를 들면 2.15가 어느 정도의 양의 상관관계인지를 가늠하기가 쉽지 않음
#공분산을 표준화 시킨 상관계수를 보다 많이 이용
#상관계수는 -1에서 1 사이의 값을 가지기에 0일 경우에는 두 변수 간의 선형관계가 전혀 없다는 것을 뜻함
#보통 0.3과 0.7 사이이면, 뚜렷한 양적 선형관계로 0.7과 1.0 사이는 강한 양적 선형관계로 간주
#상관관계는 두 변수 간의 관련성을 의미할 뿐, 원인과 결과의 방향을 알려주지는 않음
np.corrcoef(X,Y)[0,1] #두 변수간에 선형관계가 없는 걸로 보임

-0.10177720316654414

In [159]:
stats.pearsonr(X,Y)

(-0.10177720316654419, 3.8102353964692405e-14)

In [163]:
df2.fillna(0)

,산불발생건수,발생장소_시도,관측일,평균기온,일최고기온,일최고기온시각,일최저기온,일최저기온시각,일평균현지기압,일최고현지기압,...,최저운고,최저운고시각,최다운량,최다운량시각,일합계일조시간,일합계일사량,일합계소형증발량,일합계대형증발량,일평균지면온도,일평균이슬점온도
0,0,강원,20140101,3.630769,6.361538,1403.384615,-0.330769,713.153846,985.015385,988.123077,...,8.000000,866.666667,8.000000,1450.000000,6.069231,6.922000,2.066667,0.0,0.130769,0.0
1,0,경북,20140101,4.980000,8.840000,1386.866667,-0.186667,762.600000,998.986667,1001.320000,...,10.000000,925.000000,5.000000,1340.000000,7.206667,9.260000,3.033333,0.0,1.653333,0.0
2,0,경북,20140102,2.540000,8.846667,1400.133333,-2.453333,1661.533333,1005.653333,1007.646667,...,10.000000,300.000000,6.000000,1720.000000,8.213333,9.880000,2.433333,0.0,1.220000,0.0
3,0,강원,20140102,0.823077,6.284615,1390.615385,-3.961538,1452.230769,992.546154,994.338462,...,10.000000,300.000000,1.500000,333.333333,8.253846,8.726000,2.166667,0.0,-0.376923,0.0
4,0,강원,20140103,1.546154,7.123077,1374.153846,-3.538462,938.846154,989.376923,992.823077,...,8.333333,1300.000000,8.500000,700.000000,3.515385,5.204000,0.650000,0.0,-0.253846,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5497,0,강원,20201229,0.757143,5.785714,1291.285714,-2.778571,954.000000,993.300000,997.528571,...,4.000000,1500.000000,10.000000,892.307692,1.778571,3.675714,0.000000,0.0,0.314286,0.0
5498,0,경북,20201230,-6.333333,0.880000,7.466667,-9.660000,2339.133333,1002.706667,1006.993333,...,1.000000,600.000000,10.000000,100.000000,7.580000,9.804000,0.000000,0.0,-2.266667,0.0
5499,0,강원,20201230,-8.864286,-1.321429,1.000000,-12.578571,2317.571429,992.007143,996.385714,...,0.000000,0.000000,10.000000,107.692308,7.300000,10.272857,0.000000,0.0,-3.742857,0.0
5500,0,강원,20201231,-8.971429,-3.500000,1477.142857,-14.442857,525.928571,996.342857,998.135714,...,0.000000,0.000000,5.846154,992.307692,7.750000,10.532857,0.000000,0.0,-6.142857,0.0
5501,0,경북,20201231,-6.380000,-1.233333,1518.600000,-11.906667,578.600000,1008.313333,1009.960000,...,2.000000,100.000000,6.533333,1326.666667,7.460000,9.684000,0.000000,0.0,-4.360000,0.0

In [164]:
for item in ['평균기온', '일최고기온', '일최고기온시각', '일최저기온',
       '일최저기온시각', '일평균현지기압', '일최고현지기압', '일최고현지기압시각', '일최저현지기압', '일최저현지기압시각',
       '일평균해면기압', '일최고해면기압', '일최고해면기압시각', '일최저해면기압', '일최저해면기압시각', '일평균상대습도',
       '일최소상대습도', '일최소상대습도시각', '일평균수증기압', '일최고수증기압', '일최고수증기압시각', '일최저수증기압',
       '일최저수증기압시각', '일평균풍속', '일합성풍속', '일합성풍향', '일최대풍속', '일최대풍속시각', '일최대풍속풍향',
       '일최대순간풍속', '일최대순간풍속시각', '일최대순간풍속풍향', '풍정합', '일최다풍향', '일강수량', '10분최다강수량',
       '10분최다강수량시각', '1시간최다강수량', '1시간최다강수량시각', '9_9 강수량', '일최심신적설', '일최심신적설시각',
       '일최심적설', '일최심적설시각', '합계깊이신적설', '일평균전운량', '일평균중하층운량', '최저운고', '최저운고시각',
       '최다운량', '최다운량시각', '일합계일조시간', '일합계일사량', '일합계소형증발량', '일합계대형증발량',
       '일평균지면온도', '일평균이슬점온도']:
    item
    X=df2[item].values
    'Covariance:{:,.2f}'.format(np.cov(X,Y)[0,1])
    'Correlation:{:,.2f}'.format(stats.pearsonr(X,Y)[0])
    'Covariance:{:,.4f}'.format(stats.pearsonr(X,Y)[1])
    '₩n'

ValueError: array must not contain infs or NaNs

In [ ]:
df.groupby('발생원인_구분').

In [30]:
df

,관측일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,...,최저운고,최저운고시각,최다운량,최다운량시각,일합계일조시간,일합계일사량,일합계소형증발량,일합계대형증발량,일평균지면온도,일평균이슬점온도
0,20140104,13:18,토,2014,1,4,16:10,경북,경북,성주,...,7.000000,1400.000000,9.200000,1100.000000,5.980000,8.805000,0.866667,NaN,0.840000,NaN
1,20140109,15:57,목,2014,1,9,16:30,경북,경북,포항 남,...,8.666667,433.333333,2.600000,360.000000,7.973333,11.495000,1.933333,NaN,-2.506667,NaN
2,20140113,12:50,월,2014,1,13,14:40,강원,강원,화천,...,10.000000,300.000000,0.500000,300.000000,8.507692,11.232000,1.700000,NaN,-4.861538,NaN
3,20140114,12:15,화,2014,1,14,15:00,경북,경북,영주,...,4.000000,800.000000,3.400000,460.000000,8.493333,11.550000,1.533333,NaN,-3.100000,NaN
4,20140115,16:23,수,2014,1,15,17:40,동부,강원,삼척,...,NaN,NaN,0.000000,300.000000,8.515385,10.890000,1.766667,NaN,-4.376923,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1260,20201216,16:42,수,2020,12,16,18:10,경북,경북,경주,...,2.000000,200.000000,1.066667,446.666667,7.906667,10.792000,NaN,NaN,-3.126667,NaN
1261,20201217,19:41,목,2020,12,18,02:20,경북,경북,울진,...,3.000000,100.000000,4.800000,1186.666667,7.893333,10.668000,NaN,NaN,-2.753333,NaN
1262,20201224,15:59,목,2020,12,24,17:20,경북,경북,의성,...,5.000000,0.000000,9.666667,473.333333,6.620000,8.832000,NaN,NaN,2.260000,NaN
1263,20201224,17:29,목,2020,12,25,08:10,경북,경북,경주,...,5.000000,0.000000,9.666667,473.333333,6.620000,8.832000,NaN,NaN,2.260000,NaN
1264,20201225,16:22,금,2020,12,25,18:20,강원,강원,영월,...,NaN,NaN,4.846154,1207.692308,8.057143,10.322857,NaN,NaN,-2.228571,NaN

In [31]:
df_group=df.groupby('피해면적_합계').count()

In [32]:
df.sort_values(by=['피해면적_합계'],ascending=True)

,관측일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,...,최저운고,최저운고시각,최다운량,최다운량시각,일합계일조시간,일합계일사량,일합계소형증발량,일합계대형증발량,일평균지면온도,일평균이슬점온도
512,20160920,14:10,화,2016,9,20,16:30,북부,강원,춘천,...,8.500000,1050.000000,4.500000,1350.000000,9.384615,17.564000,4.46,3.100000,19.076923,NaN
126,20140427,15:25,일,2014,4,27,16:35,강원,강원,양양,...,5.666667,1416.666667,10.000000,300.000000,0.100000,7.602000,1.30,0.700000,16.369231,NaN
380,20151219,20:04,토,2015,12,19,21:00,강원,강원,인제,...,7.000000,700.000000,5.000000,500.000000,6.792308,9.570000,1.60,NaN,-0.638462,NaN
765,20180216,18:59,금,2018,2,16,20:01,경북,경북,칠곡,...,NaN,NaN,9.250000,1200.000000,8.406667,10.514000,3.92,2.720000,1.573333,-14.833333
667,20170602,13:10,금,2017,6,2,15:30,남부,경북,울진,...,5.000000,475.000000,6.000000,550.000000,12.853333,25.586000,6.86,4.800000,25.226667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,20180328,06:19,수,2018,3,28,22:00,강원,강원,고성,...,NaN,NaN,9.000000,1700.000000,7.114286,16.406667,5.80,4.066667,14.200000,3.857143
636,20170506,11:42,토,2017,5,9,11:20,강원,강원,삼척,...,14.000000,100.000000,7.000000,750.000000,11.585714,26.211667,11.40,7.966667,21.985714,NaN
988,20190404,23:46,목,2019,4,5,21:30,강원,강원,강릉,...,NaN,NaN,4.615385,861.538462,11.350000,23.671429,NaN,NaN,10.650000,-7.821429
987,20190404,19:17,목,2019,4,5,18:00,강원,강원,고성,...,NaN,NaN,4.615385,861.538462,11.350000,23.671429,NaN,NaN,10.650000,-7.821429
1186,20200424,15:39,금,2020,4,27,18:00,경북,경북,안동,...,NaN,NaN,7.066667,1226.666667,11.706667,25.150000,NaN,NaN,14.200000,NaN

In [20]:
df.to_csv('fire_weather_7yr.csv',index=False)